// Per-category wholesale content from the SEO content package
// ("CDT_Website_Content_Package_Section_by_Section"). Each entry powers a
// dedicated /categories/[slug] page: h1 headline, description, trust points,
// and the "Explore …" CTA. Copy is used verbatim from the package.
export const STORE_URL = "https://cdtweb.woopsa.app/";

export const CATEGORIES = [
  {
    slug: "smoke-essentials",
    name: "Smoke Essentials",
    headline: "Everything Your Smoke Shop Counter Needs, in One Order",
    title: "Wholesale Smoke Shop Essentials in SC | CDT Distribution",
    meta: "Papers, lighters, filters & fast-moving smoke shop accessories, wholesale from CDT Distribution's Easley, SC warehouse — next-business-day delivery.",
    desc: "Papers, lighters, filters, and the everyday smoke shop accessories your customers grab without thinking twice. CDT Distribution stocks the fast-moving smoke essentials South Carolina retailers reorder every week, all from one Easley, SC warehouse — so you're not juggling three suppliers to keep this section full.",
    points: [
      "One order covers the whole smoke essentials aisle — fewer suppliers, fewer delivery windows to manage.",
      "Next-business-day delivery across Upstate and South Carolina keeps fast-turning items in stock.",
      "Wholesale pricing built for convenience store and smoke shop margins.",
    ],
    cta: "Explore Smoke Essentials",
    img: "/images/categories/cat-tobacco.png",
    imgAlt: "Wholesale smoke essentials stocked at CDT Distribution in Easley, SC",
  },
  {
    slug: "cigarettes",
    name: "Cigarettes",
    headline: "Wholesale Cigarettes, Including Our Exclusive Teton Brand",
    title: "Wholesale Cigarettes in South Carolina | CDT Distribution",
    meta: "Wholesale cigarettes for SC retailers, including Teton — CDT Distribution's exclusive value brand. Margin-friendly pricing, next-business-day delivery.",
    desc: "CDT Distribution supplies the cigarette brands South Carolina retailers sell every day, plus Teton — our exclusive value-priced brand built specifically for price-conscious shoppers. If margin on your cigarette wall matters to your bottom line, this is the category where CDT makes the biggest difference.",
    points: [
      "Teton is exclusive to CDT — a value option your competitors down the street likely don't carry.",
      "Competitive wholesale pricing designed to protect your margin, not just move volume.",
      "We know South Carolina's vape shops and multi-store c-store licensing requirements — ask us if you're setting up a new account.",
    ],
    cta: "Explore Cigarettes",
    img: "/images/categories/cat-cigarettes.png",
    imgAlt: "Wholesale cigarettes, including the exclusive Teton brand, at CDT Distribution",
  },
  {
    slug: "disposables-vaping",
    name: "Disposables & Vaping",
    headline: "Wholesale Vapes & Disposables for SC Vape Shops and C-Stores",
    title: "Wholesale Vapes & Disposables in SC | CDT Distribution",
    meta: "Popular disposables & vaping products, wholesale for South Carolina vape shops and convenience stores — next-business-day restocks from Easley, SC.",
    desc: "Vaping is the fastest-moving, fastest-changing category on the floor. CDT Distribution keeps popular disposable and vaping products in stock and moving to convenience stores and vape shops across Upstate South Carolina, with next-business-day delivery so a sold-out flavor doesn't cost you a week of lost sales.",
    points: [
      "Fast restock on the category that changes the most — next-business-day delivery statewide.",
      "Local, Easley-based account support if you have age-verification or compliance questions.",
      "Wholesale volume pricing for both single-location vape shops and multi-store c-store accounts.",
    ],
    cta: "Explore Disposables & Vaping",
    img: "/images/categories/cat-disposable.png",
    imgAlt: "Wholesale disposable vapes stocked at CDT Distribution in Easley, SC",
  },
  {
    slug: "cigarillos",
    name: "Cigarillos",
    headline: "Wholesale Cigarillos — Raw Leaf, Starting at 89¢",
    title: "Wholesale Cigarillos — Raw Leaf 89¢ | CDT Distribution",
    meta: "Raw Leaf wholesale cigarillos from 89¢ — a high-turnover register item for SC retailers, delivered next business day with the rest of your CDT order.",
    desc: "Raw Leaf cigarillos are one of CDT's best-selling, highest-turnover register items — a low price point that keeps customers coming back and a category that earns its shelf space fast. Stock the flavors your customers already ask for, wholesale, with the same next-business-day delivery as everything else in your order.",
    points: [
      "89¢ starting price point — proven impulse-buy performance at the register.",
      "Bundled into the same order and delivery as your other CDT categories — no separate cigarillo supplier needed.",
      "Popular flavor variety kept in stock for consistent reorders.",
    ],
    cta: "Explore Cigarillos",
    img: "/images/seller-rawleaf.png",
    imgAlt: "Raw Leaf cigarillos wholesale, starting at 89¢",
  },
  {
    slug: "kratom",
    name: "Kratom",
    headline: "Bulk Wholesale Kratom for South Carolina Retailers",
    title: "Bulk Wholesale Kratom in South Carolina | CDT Distribution",
    meta: "Bulk wholesale kratom for SC retailers and specialty shops — reliable supply and next-business-day delivery from CDT Distribution in Easley, SC.",
    desc: "Kratom is a fast-growing category for independent retailers and specialty shops across South Carolina, and CDT Distribution supplies it at wholesale volume with the same reliable, next-business-day delivery as the rest of your order. If you're already fielding customer requests for kratom, this is a straightforward way to add the category without adding a new supplier relationship.",
    points: [
      "One more category on the same CDT order and delivery schedule — no separate account needed.",
      "Consistent supply for a category where customers expect their regular product to be in stock.",
      "Local Easley-based team you can ask directly about product availability.",
    ],
    cta: "Explore Kratom",
    img: "/images/categories/cat-kratom.png",
    imgAlt: "Bulk wholesale kratom available from CDT Distribution in Easley, SC",
  },
  {
    slug: "general-grocery",
    name: "General Grocery",
    headline: "Wholesale Grocery Staples That Keep Your Shelves Full",
    title: "Wholesale Grocery for C-Stores in SC | CDT Distribution",
    meta: "Snacks, packaged goods & convenience store grocery staples, wholesale from CDT Distribution — one invoice, one truck, next-business-day delivery in SC.",
    desc: "The everyday grocery items customers expect to find on a quick trip in — snacks, packaged goods, and convenience store staples — supplied wholesale and delivered next business day, so an empty shelf never costs you a sale.",
    points: [
      "Core convenience store grocery items, bundled with everything else you order from CDT.",
      "Next-business-day delivery means less overstocking just to avoid running out.",
      "One invoice, one delivery truck, one less supplier to manage.",
    ],
    cta: "Explore General Grocery",
    img: "/images/categories/cat-grocery.png",
    imgAlt: "Wholesale grocery staples stocked at CDT Distribution's Easley, SC warehouse",
  },
  {
    slug: "beverage",
    name: "Beverage",
    headline: "Wholesale Beverages — Keep Every Cooler Door Full",
    title: "Wholesale Beverages for C-Stores in SC | CDT Distribution",
    meta: "The beverages South Carolina convenience stores sell every day, wholesale — reliable delivery that keeps cooler doors full without over-ordering.",
    desc: "Coolers are some of the highest-traffic real estate in your store, and an empty one is a missed sale every time. CDT Distribution supplies the beverages South Carolina convenience stores sell every day, wholesale, with the reliable delivery schedule to keep coolers stocked without over-ordering.",
    points: [
      "High-margin cooler category kept in stock with next-business-day delivery.",
      "Order beverages alongside grocery, smoke, and vape in a single CDT order.",
      "Wholesale pricing that protects cooler-category margin.",
    ],
    cta: "Explore Beverages",
    img: "/images/categories/cat-beverage.png",
    imgAlt: "Wholesale beverages for convenience store coolers from CDT Distribution",
  },
  {
    slug: "mobile-accessories",
    name: "Mobile Accessories",
    headline: "Wholesale Mobile Accessories — Boost Plus",
    title: "Wholesale Mobile Accessories — Boost Plus | CDT Distribution",
    meta: "Boost Plus wholesale mobile accessories — chargers, cables, cases & digital scales. High-margin register-area impulse buys for SC retailers.",
    desc: "Chargers, cables, phone cases, and digital scales — Boost Plus is CDT's mobile accessories line, built for the register-area impulse buys that add easy margin to every transaction. Stock a category customers didn't plan to buy until they saw it.",
    points: [
      "Boost Plus is a CDT-exclusive line — a category differentiator versus other local suppliers.",
      "High-margin, low-footprint impulse category, easy to merchandise near checkout.",
      "Wholesale pricing on both accessories and digital scales.",
    ],
    cta: "Explore Mobile Accessories",
    img: "/images/seller-accessories.png",
    imgAlt: "Boost Plus wholesale mobile accessories from CDT Distribution",
  },
  {
    slug: "automotive",
    name: "Automotive",
    headline: "Wholesale Automotive Supplies for C-Stores & Gas Stations",
    title: "Wholesale Automotive Supplies in SC | CDT Distribution",
    meta: "Motor oil, wiper fluid, air fresheners & c-store automotive basics, wholesale from CDT Distribution — next-business-day delivery across South Carolina.",
    desc: "Motor oil, wiper fluid, air fresheners, and the basic automotive items customers expect to find at a convenience store or gas station — supplied wholesale, delivered on the same next-business-day schedule as the rest of your CDT order.",
    points: [
      "Round out your store's convenience offering without a separate automotive supplier.",
      "Next-business-day delivery keeps commonly-needed items like wiper fluid and oil in stock.",
      "Wholesale pricing built for c-store and gas station margins.",
    ],
    cta: "Explore Automotive",
    img: "/images/categories/cat-automotive.png",
    imgAlt: "Wholesale automotive supplies for convenience stores from CDT Distribution",
  },
  {
    slug: "health-care",
    name: "Health Care",
    headline: "Wholesale Health & Personal Care Products",
    title: "Wholesale Health & Personal Care in SC | CDT Distribution",
    meta: "Over-the-counter & personal care items for South Carolina convenience stores, wholesale from CDT Distribution with next-business-day delivery.",
    desc: "The over-the-counter and personal care items customers pick up on the go — supplied wholesale to South Carolina convenience stores and retailers, with the same reliable next-business-day delivery you get on every CDT category.",
    points: [
      "Keep a health & personal care section stocked without a separate supplier relationship.",
      "Next-business-day delivery across Upstate and South Carolina.",
      "Wholesale pricing designed for convenience store margins.",
    ],
    cta: "Explore Health Care",
    img: "/images/categories/cat-healthcare.png",
    imgAlt: "Wholesale health and personal care products from CDT Distribution",
  },
];

export const getCategory = (slug) => CATEGORIES.find((c) => c.slug === slug);
